name: Binance EMA Scanner

on:
  schedule:
    # 4H candle close + 5 minute buffer
    - cron: "5 0,4,8,12,16,20 * * *"

    # 1D candle close + 5 minute buffer
    - cron: "5 0 * * *"

  workflow_dispatch:
    inputs:
      timeframe:
        description: "Timeframe to scan manually"
        required: true
        default: "4h"
        type: choice
        options:
          - "4h"
          - "1d"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore duplicate protection state
        uses: actions/cache/restore@v4
        with:
          path: state.json
          key: ema-alert-state-${{ github.run_id }}
          restore-keys: |
            ema-alert-state-

      - name: Run Binance EMA Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then

            if [ "${{ github.event.schedule }}" = "5 0 * * *" ]; then
              TIMEFRAME="1d"
            else
              TIMEFRAME="4h"
            fi

          else
            TIMEFRAME="${{ inputs.timeframe }}"
          fi

          echo "Running Binance EMA Scanner: $TIMEFRAME"

          python scanner.py "$TIMEFRAME"

      - name: Save duplicate protection state
        uses: actions/cache/save@v4
        with:
          path: state.json
          key: ema-alert-state-${{ github.run_id }}
